phrase:
  access_token: "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"
  
  project_id: "ab434927896287462d544ba99e6dec9e"

  file_format: "html"

  push:

    sources:

    - file: "./index_<locale_code>.html"
    params: 
     format_options:
      document_id: "3837"

  pull:

    targets:

    - file: "./index_<locale_code>.html"
    
